### ISSUE TITLE
关于项目名称

### ISSUE THREAD

**Issue by mili-tan** [xireiki/AhaDNS#1]
嗨，xireiki 您好呀！
非常感谢您的努力，在 Go 上实现 HTTP-DNS 的 Alidns 客户端，不仅简化了部署还添加 DNS over TLS 支持，
您的作品相比我之前的工作更加出色，一定能够帮助更多人更加轻松的使用  HTTP-DNS 的 Alidns！

但是我有一个小小的建议和请求，您可以更改项目名称吗？
ArashiDNS 是由我开发的半商业性质的 DNS 工具，其中有一些开源软件也包含在 ArashiDNS 的名称空间下比如 ArashiDNS.Aha，
如果您同样使用 ArashiDNS 名称，可能带来一些混淆或不便，可以麻烦您修改下项目名称吗？
Aha-Go 也许也是一个不错的名字？

最后再次感谢您的工作，也祝您有个愉快的周末！

**Comment by xireiki** [comment]
> 嗨，xireiki 您好呀！ 非常感谢您的努力，在 Go 上实现 HTTP-DNS 的 Alidns 客户端，不仅简化了部署还添加 DNS over TLS 支持， 您的作品相比我之前的工作更加出色，一定能够帮助更多人更加轻松的使用 HTTP-DNS 的 Alidns！
> 
> 但是我有一个小小的建议和请求，您可以更改项目名称吗？ ArashiDNS 是由我开发的半商业性质的 DNS 工具，其中有一些开源软件也包含在 ArashiDNS 的名称空间下比如 ArashiDNS.Aha， 如果您同样使用 ArashiDNS 名称，可能带来一些混淆或不便，可以麻烦您修改下项目名称吗？ Aha-Go 也许也是一个不错的名字？
> 
> 最后再次感谢您的工作，也祝您有个愉快的周末！

@mili-tan 好的，非常抱歉，我会在今天想一个名字并修改它的

**Comment by mili-tan** [comment]
> > 嗨，xireiki 您好呀！ 非常感谢您的努力，在 Go 上实现 HTTP-DNS 的 Alidns 客户端，不仅简化了部署还添加 DNS over TLS 支持， 您的作品相比我之前的工作更加出色，一定能够帮助更多人更加轻松的使用 HTTP-DNS 的 Alidns！
> > 但是我有一个小小的建议和请求，您可以更改项目名称吗？ ArashiDNS 是由我开发的半商业性质的 DNS 工具，其中有一些开源软件也包含在 ArashiDNS 的名称空间下比如 ArashiDNS.Aha， 如果您同样使用 ArashiDNS 名称，可能带来一些混淆或不便，可以麻烦您修改下项目名称吗？ Aha-Go 也许也是一个不错的名字？
> > 最后再次感谢您的工作，也祝您有个愉快的周末！
> 
> @mili-tan 好的，非常抱歉，我会在今天想一个名字并修改它的

谢谢您，您也辛苦了！
